MvcWebApp/Models/DCandidate.cs
namespace MvcWebApp.Models
{
    public class DCandidate
    {
        public DCandidate() { } 
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Email { get; set; }
        public string PhoneNumber { get; set; }
        public string Zipcode { get; set; }
        public int Id { get; set; }
    }
}

MvcWebApp/Models/ErrorViewModel.cs
namespace MvcWebApp.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

MvcWebApp/Models/MPersistenceConfig.cs
namespace MvcWebApp.Models
{
    public class MPersistenceConfig
    {
        public MPersistenceConfig() { }
        public string UseSql { get; set; }
        public string Seed { get; set; }
    }
}

MvcWebApp/Controllers/CandidatesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using AutoMapper;
using Core.Contacts.Application.Interfaces;
using Core.Contacts.Domain.Models;
using Core.Contacts.Exception;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using MvcWebApp.Models;

namespace WebApplication1.Controllers
{
    public class CandidatesController : Controller
    {
        private readonly ICandidateService _candidateService;
        private MapperConfiguration config;
        
        public CandidatesController(ICandidateService _service)
        {
            this._candidateService = _service;
            config = new MapperConfiguration(cfg => { cfg.CreateMap<MCandidate, DCandidate>(); });
        }

        // GET: Candidates
        public async Task<IActionResult> Index(string firstName, string lastName, string email, string phone, string zipcode)
        {
            if (firstName==null && lastName==null && email==null && phone==null && zipcode==null)
                return View(new List<MCandidate>());
            var result = await _candidateService.FindCandidate(firstName, lastName, email, phone, zipcode);
                          
            return View(result);
        }
        
        // GET: Candidates/Details/5
        public async Task<IActionResult> Details(int id)
        {


            var candidate = await _candidateService.FindAsync(id);
            if (candidate == null)
            {
                return NotFound();
            }

            return View(candidate);
        }

        // GET: Candidates/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Candidates/Create
        [HttpPost]
       [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,FirstName,LastName,Email,PhoneNumber,Zipcode")] DCandidate candidate)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    int id = await _candidateService.CreateCandidate(candidate.FirstName, candidate.LastName, candidate.Email, candidate.PhoneNumber, candidate.Zipcode);
                    return RedirectToAction(nameof(Index));
                }
                catch (CandidateException ex)
                {
                    ModelState.AddModelError("", ex.Message);
                }   
               
            }
            return View(candidate);
        }

        // GET: Candidates/Edit/5
        public async Task<IActionResult> Edit(int id)
        {
            if (id == null )
            {
                return NotFound();
            }

            MCandidate entidad = await _candidateService.FindAsync(id);
           
            if (entidad == null)
            {
                return NotFound();
            }
            var mapper = new Mapper(config);
            var candidate = mapper.Map<MCandidate, DCandidate>(entidad);
            return View(candidate);
        }

        // POST: Candidates/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,FirstName,LastName,Email,PhoneNumber,Zipcode")] DCandidate candidate)
        {
            if (id != candidate.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    int updateCount = await _candidateService.UpdateAsync(candidate.Id,
                                                                     candidate.FirstName,
                                                                     candidate.LastName,
                                                                     candidate.Email,
                                                                     candidate.PhoneNumber,
                                                                     candidate.Zipcode);

                    return RedirectToAction(nameof(Index));
                }
                catch (CandidateException ex)
                {
                    ModelState.AddModelError("", ex.Message);
                }
        }
            return View(candidate);
        }

        // GET: Candidates/Delete/5
        public async Task<IActionResult> Delete(int id)
        {
            if (id == null )
            {
                return NotFound();
            }

            var candidate = await _candidateService.FindAsync(id);
            if (candidate == null)
            {
                return NotFound();
            }
            var mapper = new Mapper(config);
            var model = mapper.Map<MCandidate, DCandidate>(candidate);
            return View(model);
        }

        // POST: Candidates/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
                try
                {
                    int deleteCount = await _candidateService.Remove(id);
                }
                catch (Exception)
                {

                    return NotFound();
                }
                
            
            return RedirectToAction(nameof(Index));
        }

       

    }
}

MvcWebApp/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using MvcWebApp.Models;
using System.Diagnostics;

namespace MvcWebApp.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

MvcWebApp/Views/Candidates/Create.cshtml
@model DCandidate

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Candidate</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="FirstName" class="control-label"></label>
                <input asp-for="FirstName" class="form-control" />
                <span asp-validation-for="FirstName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="LastName" class="control-label"></label>
                <input asp-for="LastName" class="form-control" />
                <span asp-validation-for="LastName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Email" class="control-label"></label>
                <input asp-for="Email" class="form-control" />
                <span asp-validation-for="Email" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="PhoneNumber" class="control-label"></label>
                <input asp-for="PhoneNumber" class="form-control" />
                <span asp-validation-for="PhoneNumber" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Zipcode" class="control-label"></label>
                <input asp-for="Zipcode" class="form-control" />
                <span asp-validation-for="Zipcode" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

MvcWebApp/Views/Candidates/Delete.cshtml
@model DCandidate

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Candidate</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.FirstName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.FirstName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.LastName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.LastName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Email)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Email)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.PhoneNumber)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.PhoneNumber)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Zipcode)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Zipcode)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

MvcWebApp/Views/Candidates/Details.cshtml
@using Core.Contacts.Domain.Models;
@model MCandidate

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Candidate</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.FirstName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.FirstName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.LastName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.LastName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Email)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Email)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.PhoneNumber)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.PhoneNumber)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Zipcode)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Zipcode)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model?.Id">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

MvcWebApp/Views/Candidates/Edit.cshtml
@model DCandidate

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Candidate</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="FirstName" class="control-label"></label>
                <input asp-for="FirstName" class="form-control" />
                <span asp-validation-for="FirstName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="LastName" class="control-label"></label>
                <input asp-for="LastName" class="form-control" />
                <span asp-validation-for="LastName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Email" class="control-label"></label>
                <input asp-for="Email" class="form-control" />
                <span asp-validation-for="Email" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="PhoneNumber" class="control-label"></label>
                <input asp-for="PhoneNumber" class="form-control" />
                <span asp-validation-for="PhoneNumber" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Zipcode" class="control-label"></label>
                <input asp-for="Zipcode" class="form-control" />
                <span asp-validation-for="Zipcode" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

MvcWebApp/Views/Candidates/Index.cshtml
@using Core.Contacts.Domain.Models;
@model IEnumerable<MCandidate>
@{
    ViewData["Title"] = "Index";
}
<h1>Index</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>

<form asp-action="Index" method="get" class="form-container">
    <div class="form-group">
        <label for="firstName">First Name:</label>
        <input type="text" name="firstName" id="firstName" class="form-control" />
    </div>
    <div class="form-group">
        <label for="lastName">Last Name:</label>
        <input type="text" name="lastName" id="lastName" class="form-control" />
    </div>
    <div class="form-group">
        <label for="email">Email:</label>
        <input type="text" name="email" id="email" class="form-control" />
    </div>
    <div class="form-group">
        <label for="phone">Phone:</label>
        <input type="text" name="phone" id="phone" class="form-control" />
    </div>
    <div class="form-group">
        <label for="zipcode">Zip Code:</label>
        <input type="text" name="zipcode" id="zipcode" class="form-control" />
    </div>
    <div class="form-group">
        <button type="submit" class="btn btn-primary">Search</button>
    </div>
</form>


<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.FirstName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.LastName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Email)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.PhoneNumber)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Zipcode)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.FirstName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.LastName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Email)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.PhoneNumber)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Zipcode)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.Id">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.Id">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.Id">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>

MvcWebApp/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div >

     <div class="container">
      <div class="text">
        <h1>Welcome to ContactTracking</h1>
    <p>In Appsettings.json you can enable database Configurations.</p>
    <code>
      "Persistence": {
        "UseSql": "N",
        "Seed": "Y"
      }
    </code>
    <p>For Sql Server:</p>
    <ol>
      <li>Set "UseSql": "Y"</li>
      <li>Start a Power shell console.</li>
      <li>Enter to ContactTracking/Tools</li>
      <li>Run:
        <code>./BUILDRunSQLServer.ps1</code>
      </li>
      <li>Wait while a docker container is created, also the database is created and migrations executed</li>
      <li>Run MvcWebApp project with IIS Express</li>
    </ol>    
    </div>
      <div class="image">
          <a class="navbar-brand" asp-area="" asp-controller="Candidates" asp-action="Index">
            <img src="/images/contacts.png" alt="search candidates">
          </a>
      </div>
    </div>
    
    
</div>
<style>
  h1 {
    font-size: 2em;
    font-weight: bold;
  }
  
  code {
    background-color: lightgray;
    padding: 0.2em;
    font-family: "Courier New", Courier, monospace;
  }
  
  ol {
    list-style-type: decimal;
  }

  .container {
        display: flex;
        flex-direction: row;
        justify-content: space-between;
        align-items: center;
      }
  .text {
    flex: 1;
  }
  
  .image {
    flex: 1;
    display: flex;
    justify-content: center;
    align-items: center;
  }
  
  img {
    max-width: 100%;
    height: auto;
  }
</style>

MvcWebApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Frodorix</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/MvcWebApp.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Candidates" asp-action="Index">
                    <img width="50px" height="50px" class="logo" src="/images/contacts.png"/>
                </a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Candidates" asp-action="Index">Candidates</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - Contacts WebApp - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>